#!/bin/bash
# tools.sh - Display all available development tools

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_DIR="$(dirname "$SCRIPT_DIR")"

echo "🛠️  Clariti Development Tools"
echo "============================"
echo ""

echo "📋 Available Scripts:"
echo "-------------------"
echo "🧪 ./local/dev/test.sh           - Run all tests with coverage (if exists)"
echo "🔍 ./local/dev/lint.sh           - Run golangci-lint code quality checks"
echo "🚀 ./local/benchmarks/benchmark.sh - Run configurable performance benchmarks"
echo "🔬 ./local/benchmarks/analyze.sh - Advanced benchmark analysis & comparison"
echo "🛠️  ./local/dev/tools.sh          - Show this help menu"
echo ""

echo "🔧 HTTPS & Security:"
echo "-------------------"
echo "🔐 ./local/certs/generate-certs.sh - Generate development certificates"
echo "🧪 ./local/certs/test-https.sh     - Test HTTPS functionality"
echo ""

echo "📁 Configuration Examples:"
echo "-------------------------"
echo "⚙️  ./local/config/config.example.yaml - Basic configuration template"
echo "🔒 ./local/config/config.https.yaml    - HTTPS configuration example"
echo ""

echo "⚡ Quick Commands:"
echo "----------------"
echo "# Run quality checks:"
echo "./local/dev/lint.sh"
echo ""
echo "# Run benchmarks with options:"
echo "./local/benchmarks/benchmark.sh --help"
echo "./local/benchmarks/analyze.sh --baseline"
echo "./local/benchmarks/analyze.sh --compare"
echo ""

echo "🔧 Development Workflow:"
echo "----------------------"
echo "1. Code changes                      - Edit your Go files"
echo "2. ./local/dev/lint.sh               - Check code quality"
echo "3. go test ./...                     - Verify functionality"
echo "4. ./local/benchmarks/benchmark.sh   - Check performance"
echo "5. git commit                        - Commit your changes"
echo ""

echo "📊 Benchmark Commands:"
echo "--------------------"
echo "# Generate performance baseline:"
echo "./local/benchmarks/analyze.sh --baseline"
echo ""
echo "# Run benchmarks with custom timeout:"
echo "./local/benchmarks/benchmark.sh --timeout 2m"
echo ""
echo "# Compare current performance:"
echo "./local/benchmarks/analyze.sh --compare"
echo ""

echo "📁 Directory Structure:"
echo "----------------------"
echo "local/"
echo "├── dev/           # Development tools (lint, test scripts)"
echo "├── benchmarks/    # Performance testing tools and results"
echo "├── config/        # Configuration examples"
echo "├── certs/         # HTTPS certificates and tools"
echo "└── README.md      # Documentation"
echo ""

echo "✅ All tools are ready to use!"
echo "💡 Most scripts support --help for detailed options"
